platform :ios, "6.0"
workspace 'OLImperialMenuDemo'

# OLCategoryHelper
pod 'OLCategoryHelper/UIView+ViewFrameGeometry', '~> 0.0.2'
pod 'OLCategoryHelper/NSString+BOOL', '~> 0.0.2'
pod 'OLCategoryHelper/UIDevice+Resolutions', '~> 0.0.2'